### PR TITLE
Spanish Translation (Partial)

### PR DESCRIPTION
**Pull request by vacilagodzila**
Hello, I'm glad to be submitting what seems to be the first spanish translation for this project.

**About the Translation:**

- 1040 translatable words have been translated to spanish (not counting codes, links, paths nor words that are suposed to remain untranslated). I will finish the translation somewhere around the next weekend, hopefully. Would be great if you could merge this partial work, nonetheless.

**About the vocabulary:**

- I had a hard time deciding for a propper way to translate "Coworker". There isn't an exact translation for this word in spanish. I thought something like "colega" (colleague in english) would do, but "colega" is closer to "friend" than to "coworker". So, we should work on finding something that works for "coworker" in spanish since "Compañero de trabajo" sounds funny, unattractive and is too long. Could affect the product.

- Also don't know if "guild" translated to "gremio" in spanish works in this context.

**Typos:**

I think I've found a couple mistakes: on [cards-marketing-pricing](https://github.com/vacilagodzila/translations/blob/master/cards-marketing-pricing/en.json) (line 5, dont know what "delivered" is suposed to mean) and on [cards-page-group-main](https://github.com/vacilagodzila/translations/blob/master/cards-page-group-main/en.json) (line 10, I think "live" isn't meant to be there). Of course, I don't know the project that well so I could be mistaken, just wanted to point that out given that it could have affected my translation.

Any suggestion is welcome. Also willing to keep on helping with translations for this and any project to spanish, of course. Ty!

### CODE REVIEW

**Comment by rtkhanas** [comment]
Wow, @vacilagodzila , that looks like a huge work, what you a lot!

**About the vocabulary**

- Where did you find a "coworker" word? Cannot find it.
- It seems like a "gremio" is a good word for a "guild". I tried to translate it to Ukrainian and Russian languages and looks like it has similar meaning.

**Typos**

In both cases I think it is ok. First case is a headline so maybe it looks a bit weird. A "live card" is how we named a contact record in our product. It is always up to date, that is why it is "live". No need to update it manually.

But thanks for you suggestion, maybe we should change those sentences, since they may be not clear for potential users!

**Comment by vacilagodzila** [comment]
Copy that!

When I say "coworker" I'm also refering to other words like "coworkers, coworking software..." that can be found throught out the files. As I said, not sure in general how to attack that word in spanish. "Compañero de trabajo" does the job but is not all that convincing to me. 

Maybe I'll finish all files remaining later in the day, when I get home.

**Comment by rtkhanas** [comment]
Hm, Spanish wiki article is named «Trabajo cooperativo». https://es.wikipedia.org/wiki/Trabajo_cooperativo May that be an option?

**Comment by vacilagodzila** [comment]
«Trabajo Cooperativo» it's not exactly what I'd be aiming for since it's too general. But I do like the use of the word «cooperativo», I might try to work that out on the files later when I make my ultimate PR with these fixes. Thank you for the suggestion!

**Pull request merged**
